global:
  resolve_timeout: 5m

route:
  receiver: default
  group_by: ['alertname', 'service', 'job']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: critical
      repeat_interval: 1h

receivers:
  - name: default
    webhook_configs:
      - url: 'http://alert-tester:5001/alerts'

  - name: critical
    webhook_configs:
      - url: 'http://alert-tester:5001/alerts'

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'service']
